package com.sqscon.mongo_consumer_service.enums;

public enum EventType {

    BUYING_CREATED,
    BUYING_UPDATED,
    CHALLAN_COUNT_UPDATED,
    CUSTOMER_DOCKET_UPDATED,
    DEALER_DOCKET_UPDATED,
    SALES_DOCKET_UPDATED,
    AD_BUYING_ADDRESS_UPDATED,
    BOOKING_ADDRESS_UPDATED,
    AADHAR_INITIATED,
    AD_BOOKING_ADDRESS_UPDATED,
    AD_SET_NAME_FINAL_SIMILARITY,
    PRESIGNED_URL_GENERATION,
    DOCUMENT_IMAGE_NOTIFICATION,
    DOCUMENT_REMARK_UPDATE,
    DOCUMENT_OPERATION_BUYING_UPDATE,
    DOCUMENT_OPERATION_BOOKING_UPDATE

}